name: Update Docker Hub Description

on:
  pull_request:
    branches: [ master ]
    types: [ closed ] # Runs when a pull request is merged into master

env:
  IMAGE_NAME: middleearthmedia/php-alpine

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
